apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: myweb
          image: nginx
          ports:
            - containerPort: 80