apiVersion: apps/v1
kind: Deployment
metadata:
    name: mywebserver
    labels:
        app: httpd
spec:
    replicas: 6
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 2
            maxUnavailable: 3
    selector:
       matchLabels:
           app: httpd
    template:
        metadata:
           labels:
               app: httpd
        spec:
            containers:
                - name: myhttpd
                  image: httpd:2
                  ports:
                    - containerPort: 80