apiVersion: apps/v1
kind: Deployment
metadata:
    name: sample-deployment
    labels:
        app: my-deployment

spec:
    replicas: 4
    selector:
        matchLabels:
            app: my-deployment
    template:
        metadata:
            labels:
                app: my-deployment
        spec:
            containers:
                - name: my-nginx
                  image: nginx
                  ports:
                    - containerPort: 8080