apiVersion: apps/v1
kind: Deployment
metadata:
    name: account-deployment
    labels:
        app: account
spec:
    replicas: 1
    selector:
        matchLabels:
            app: account
    template:
        metadata:
            labels:
                app: account
        spec:
            containers:
              - name: account-container
                image: account-service-devops
                ports:
                  - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
    name: account-service
    labels:
        app: account
spec:
    selector:
        app: account
    type: NodePort
    ports:
      - port: 8081
        targetPort: 8081
        protocol: TCP