apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-deployment-with-all
    labels:
        app: db-all
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db-all
    template:
        metadata:
            labels:
                app: db-all
        spec:
            containers:
              - name: mysql-container-with-all
                image: mysql
                env:
                  - name: MYSQL_DATABASE
                    valueFrom:
                        configMapKeyRef:
                            name: db-configmap
                            key: mysql-database-name
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: db-secret
                            key: mysql-password
                volumeMounts:
                  - name: mysql-volume
                    mountPath: /var/lib/mysql
            volumes:
              - name: mysql-volume
                persistentVolumeClaim:
                    claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-devops
spec:
    type: NodePort
    selector:
        app: db-all
    ports:
      - port: 3306
        targetPort: 3306
        protocol: TCP
               