apiVersion: v1
kind: PersistentVolume
metadata:
    name: db-pv
    labels:
        app: pv
spec:
    accessModes:
      - ReadWriteOnce
    capacity:
        storage: 5Gi
    hostPath:
        path: /data/db-pv