apiVersion: apps/v1
kind: Deployment
metadata:
    name: payment-deployment
    labels:
        app: payment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payment
    template:
        metadata:
            labels:
                app: payment
        spec:
            containers:
              - name: payment-container
                iamge: sukumarrkv/payment-service-devops
                ports:
                  - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
    name: payment-service
    labels:
        app: payment
spec:
    selector:
        app: payment
    type: NodePort
    ports:
      - port: 8082
        targetPort: 8082
        protocol: TCP