apiVersion: apps/v1
kind: Deployment
metadata:
    name: cip-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: cip
    template:
        metadata:
            labels:
                app: cip
        spec:
            containers:
                - name: cip-nginx
                  image: nginx
                  ports:
                    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: cip-service
    labels:
        app: cip
spec:
    type: ClusterIP
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
    selector:
        app:  cip