apiVersion: apps/v1
kind: Deployment
metadata:
    name: lb-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: lb
    template:
        metadata:
            lables:
                app: lb
        spec:
            containers:
                - name: lb-nginx
                  image: nginx
                  port:
                    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: lb-service 
    labels:
        app: lb 
spec:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
    selector:
        app: lb
    