apiVersion: apps/v1
kind: Deployment
metadata:
    name: np-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: np
    template:
        metadata:
            labels:
                app: np
        spec:
            containers:
                - name: np-nginx
                  image: nginx
                  ports:
                    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    name: np-service
    labels:
        app: np
spec:
    type: NodePort
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
    selector:
        app: np