apiVersion: v1
kind: Service
metadata:
  name: couponservice
  labels:
    app: coupon
spec:
  selector:
    app: coupon
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30101