apiVersion: apps/v1
kind: Deployment
metadata:
  name: coupon-app
  labels:
   app: coupon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coupon
  template:
    metadata: 
      name: coupon-app
      labels:
        app: coupon
    spec:
      containers:
        - name: coupon-app
          image: sukumarrkv/couponservice
       