apiVersion: v1
kind: Service
metadata:
  name: productservice
  labels:
    app: product
spec:
  selector:
    app: product
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30102