apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
         app: product
    spec:
      containers:
        - name: product-app
          image: sukumarrkv/productservice