apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
               app: mysql
        spec:
            containers:
                - name: mysql-container 
                  image: mysql
                  env:
                    - name: MYSQL_DATABASE
                      valueFrom:
                        configMapKeyRef:
                          name: mysql-configmap
                          key: mysql-database-name
                    - name: MYSQL_ROOT_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mysql-secret
                          key: mysql-password
                  ports:
                    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
        app: mysql
spec:
    type: NodePort
    selector:
       app: mysql
    ports:
      - port: 3306
        targetPort: 3306
    
